module: "LoopRace"
device_id: 7
epochs: 5
train_data:
  file: "DATA/susy/train.txt"
  dataset: "csv"
  csv:
    sep: ","
    label_header: 0
    centering_info: "DATA/susy/centering_info.npz"
    use_only: 8
  sampler: "race"
  race:
    batch_size: 1024
    sampling_rate: 0.8
    accept_prob: 0.1
    warmup_niter: 5
    race_update_freq: 1000000000 # per x iterations 
test_data:
  file: "DATA/susy/test.txt"
  dataset: "csv"
  csv:
    sep: ","
    label_header: 0
    centering_info: "DATA/susy/centering_info.npz"
    use_only: 8
  sampler: "simple"
  simple:
    batch_size: 1024
progress_test_data:
  file: "DATA/susy/valid.txt"
  dataset: "csv"
  csv:
    sep: ","
    label_header: 0
    centering_info: "DATA/susy/centering_info.npz"
    use_only: 8
  sampler: "simple"
  simple:
    batch_size: 1024
progress_train_data:
  file: "DATA/susy/train.txt"
  dataset: "csv"
  csv:
    sep: ","
    label_header: 0
    centering_info: "DATA/susy/centering_info.npz"
    use_only: 8
  sampler: "simple"
  simple:
    batch_size: 1024
np_seed: 101
race:
  num_classes: 2
  num_bucket: 10000  
  device_id : -1 # to do on cpu. test device as well later
  recovery : "mean" # mean recovery
  lsh_function:
    name: "srp_torch"
    srp_torch:
      dimension: 8
      num_bits: 16
      num_hash : 100
      seed: 101
      device_id: -1

model:
  name: "MLPSG"
  MLPSG:
    input_dim: 8
    num_layers: 4
    hidden_size: 500
    num_class: 2
optimizer:
  name: "adam"
  adam:
    lr: 0.001
    weight_decay: 0
loss:
  name: "BCE"
progress_evaluator:
  name: "simple_print"
  simple_print:
          #eval_itr: 500000000
      eval_itr: 1000
      eval_epoch: 1
      csv_dump: "DATA/susy/record/log.train.sg8.L500.N4_race_sr0.8_Noupdate.csv"
      skip_0: 0
metrics: "acc,auc"
binary: True
